name: Lint

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  check-eol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check line endings
        uses: erclu/check-crlf@v1.2.0

  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0

      - name: Install eslint
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true

  lint-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          clang_format: true