name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    #container: rebble/pebble-sdk:4.5-2
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
      - run: |
        sudo apt update
        sudo apt install python2
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
        sudo python2 get-pip.py
        sudo -H python2.7 -m pip install -U pip setuptools wheel virtualenv
        sudo apt install python2-dev
        sudo apt install libnode-dev npm

      - run: ls -al

      - run: pebble --help
