name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    #container: rebble/pebble-sdk:4.5-2
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt update
      - run: sudo apt install python2

      - run: ls -al

      - run: pebble --help
