name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    #container: rebble/pebble-sdk:4.5-2
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update \
          sudo apt install python2 \
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

      - run: ls -al

      - run: pebble --help
