name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SDK_VER: 4.3
    steps:
      - uses: actions/checkout@v3

      - name: Cache date
        run: echo "DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Filename friendly date
        run: echo "BUILD_DATE=$(echo $DATE | sed -r -e 's/:/./g' -e 's/ /_/g')" >> $GITHUB_ENV

      - name: Store branch name
        run: echo "BUILD_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Store commit hash
        run: echo "BUILD_COMMIT=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Generate output name
        run: echo "NAME=${BUILD_DATE}_${BUILD_BRANCH}_${BUILD_COMMIT}_Pebble-Casio-WV58DE" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python2
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          sudo python2 get-pip.py
          sudo -H python2.7 -m pip install -U pip setuptools wheel virtualenv
          sudo apt install python2-dev
          sudo apt install libnode-dev npm
          rm get-pip.py

      - name: Bootstrap Pebble SDK
        run: |
          mkdir ~/pebble-dev
          cd ~/pebble-dev
          wget https://developer.rebble.io/s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-4.5-linux64.tar.bz2
          tar -xf pebble-sdk-4.5-linux64.tar.bz2
          cd pebble-sdk-4.5-linux64
          echo "$HOME/pebble-dev/pebble-sdk-4.5-linux64/bin" >> $GITHUB_PATH
          if [ "$(grep 'pebble-sdk-homebrew' requirements.txt)" ]; then cp requirements.txt requirements.txt.OLD; grep -v pypkjs requirements.txt.OLD > requirements.txt; echo 'git+https://github.com/pebble/pypkjs.git' >> requirements.txt; fi
          if [ "$(grep 'sdk.getpebble.com' pebble-tool/pebble_tool/sdk/manager.py)" ]; then sudo mv pebble-tool pebble-tool.OLD; sudo git clone https://github.com/pebble-dev/pebble-tool.git; fi
          [ -e .env ] || virtualenv --python=python2.7 .env
          . .env/bin/activate
          pip install -r requirements.txt
          pip install -r pebble-tool/requirements.txt
          deactivate

      - name: Install Pebble SDK
        run: yes | pebble sdk install $SDK_VER

      - name: Build app
        run: pebble build --sdk $SDK_VER

      - name: Upload app
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.NAME }}
          path: build/*.pbw

  release:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download files
        uses: actions/download-artifact@v3

      - name: Zip each folder
        run: |
          for d in */; do
            echo "Zipping ${d} into ${d%/}.zip"
            zip -r "${d%/}.zip" "$d"
            echo "Deleting ${d}"
            rm -rf "$d"
          done
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *
